[phases.setup]
nixPkgs = ["nodejs", "chromium", "glib", "nss", "fontconfig", "cups", "pango", "cairo", "atk", "at-spi2-atk", "dbus", "libdrm", "mesa", "libxkbcommon"]

[phases.build]
cmds = ["npm install"]
